feat : Added Malayalam translation #231
cicirello/user-statistician pull request #235
Opened 2023-10-02 18:05 UTC by Sarthak027

## Summary
Adding Malayalam translations

## Closing Issues
closes #231 

## Types of changes

- [x] I have read the [**CONTRIBUTING**](https://github.com/cicirello/.github/blob/main/CONTRIBUTING.md) document.
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Improvements to existing code, such as refactoring or optimizations (non-breaking)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2023-10-02 18:32 UTC, Viveksati5143 requested changes

2023-10-02 18:32 UTC, Viveksati5143 commented on src/locales/ml.json
> +    "titleTemplate": "{0}-ന്റെ GitHub പ്രവർത്തനം",
Is there some word for GitHub in Malayalam?

2023-10-02 18:46 UTC, cicirello commented on src/locales/ml.json
> +    "titleTemplate": "{0}-ന്റെ GitHub പ്രവർത്തനം",
@Viveksati5143 thanks for reviewing.
@Sarthak027 thanks for confirming.

2023-10-02 18:48 UTC, merged

2023-10-02 18:52 UTC, cicirello commented
Thanks for contributing @Sarthak027. Later this week I'll create a release that includes this.

2023-10-02 18:58 UTC, Sarthak027 commented
Sure @cicirello.

2023-10-04 17:13 UTC, cicirello commented
@Sarthak027 I just released v1.21.0 that includes this translation (also available via major tag v1). 🚀 Thank you again for contributing.